#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# History
HISTFILE=~/.histfile
HISTSIZE=5000
SAVEHIST=5000

# Editor
EDITOR=/usr/bin/vim
GIT_EDITOR=/usr/bin/vim

# Aliases
alias gs="git status"
