#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Shell vars
HISTFILE=~/.histfile
HISTSIZE=5000
SAVEHIST=5000
EDITOR=/usr/bin/vim

# Exported vars
export GIT_EDITOR=/usr/bin/vim
export GOPATH=/Users/dave.thompson/code/golang
export PYCURL_SSL_LIBRARY=openssl

# PT
if [ -f ~/code/zsh-pt/.zshrc ]; then
  source ~/code/zsh-pt/.zshrc
fi

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
